version: 2.1
jobs:
  build:
    working_directory: ~/gui_build
    docker:
      - image: ansuel/gui-autobuild-image:2
    steps:
      - checkout
      - run:
          name: Check built type from last git log
          command: bash ./scripts/0-detect-build-type.sh
      #- restore_cache:
      #    keys: latest-file-key
      - run:
          name: Increment version from latest build
          command: bash ./scripts/1-increment_autobuild_ver.sh
      - run:
          name: Minify css and javascript
          command: bash ./scripts/1-compress_css_javascript.sh
      - run:
          name: Clone autobuild repo
          command: bash ./scripts/2-clone_autobuild_dir.sh
      - run:
          name: Update po
          command: python3 ./scripts/update_po.py
      - run:
          name: Inizialize Gui
          command: bash ./inizialize_gui.sh
      - run:
          name: Upload new build, build and latest.version
          command: bash ./scripts/3-update_autobuild_ver.sh
      - run:
          name: Committing updated po to master
          command: bash ./scripts/6-commit_po.sh
      #- save_cache:
      #    key: latest-file-key
      #    paths:
      #      - ~/gui-dev-build-auto/latest.version
      - persist_to_workspace:
          root: ~/gui_build
          paths: 
            - compressed
            - scripts
            - data
  
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: /tmp/gui_build
      - run:
          name: "Publish Release on GitHub"
          command: bash /tmp/gui_build/scripts/7-push-relese.sh

workflows:
  version: 2
  build_and_deploy:
    jobs: 
      - build
      - publish-github-release:
          requires:
            - build